addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.3.19")
addSbtPlugin("com.github.sbt"         % "sbt-release"         % "1.0.15")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.3.4")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.30")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.16")