addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.3.19")
addSbtPlugin("com.github.sbt"            % "sbt-release"         % "1.1.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.12.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
