openapi: '3.0.2'
info:
  title: Kafka Flightstream server API
  description: Kafka Flightstream server API
  contact:
    name: Bitrock
    url: https://bitrock.it/
  license:
    name: 'MIT'
    url: 'https://spdx.org/licenses/MIT.html'
  version: 1.0.0-SNAPSHOT

servers:
- url: https://flightstream-api.bitrock.it/v1/rest
  variables:
    basePath:
      enum:
      - v1
      default: v1

tags:
- name: internals
- name: ksql

paths:
  /health:
    get:
      tags:
        - internals
      x-scala-package: internals
      summary: Returns application status
      operationId: health
      responses:
        '200':
          description: Server is healthy
  /ksql:
    post:
      tags:
        - ksql
      x-scala-package: ksql
      summary: Creates a stream from a given statement
      externalDocs:
        url: https://docs.confluent.io/current/ksql/docs/developer-guide/create-a-stream.html
      operationId: createStream
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/CreateKsqlRequest'
      responses:
        '201':
          description: Stream created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/KsqlSuccessResponse'
        '400':
          description: Bad request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDescription'
        '500':
          description: Server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDescription'
  /session/clean:
    post:
      tags:
        - session
      x-scala-package: session
      summary: Cleans the session
      operationId: cleanSession
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/CleanSessionRequest'
      responses:
        '204':
          description: Session cleaned
        '500':
          description: Server error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorDescription'

components:
  schemas:
    CreateKsqlRequest:
      type: object
      required:
        - ksql
      properties:
        ksql:
          type: string
    CleanSessionRequest:
      type: object
      required:
        - streamIds
      properties:
        streamIds:
          $ref: '#/components/schemas/StreamIdList'
    StreamIdList:
      type: array
      items:
        type: string
    ErrorDescription:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    KsqlSuccessResponse:
      type: object
      required:
        - streamId
        - endpoint
      properties:
        streamId:
          type: string
        endpoint:
          type: string
