openapi: '3.0.2'
info:
  title: Kafka Flightstream server API
  description: Kafka Flightstream server API
  contact:
    name: Bitrock
    url: https://bitrock.it/
  license:
    name: 'MIT'
    url: 'https://spdx.org/licenses/MIT.html'
  version: 1.0.0-SNAPSHOT

servers:
- url: https://flightstream-api.bitrock.it/v1/rest
  variables:
    basePath:
      enum:
      - v1
      default: v1

tags:
- name: internals

paths:
  /health:
    get:
      tags:
        - internals
      x-scala-package: internals
      summary: Returns application status
      operationId: health
      responses:
        '200':
          description: Server is healthy
