@startuml
title kafka-dvs-api architecture

[kafka-dvs-api] as API
[Client] as client

node Kafka {
    database "flight_received\ntopic" as FlightTopic
    database "top_arrival_airport\ntopic" as TopArrivalAirportTopic
    database "top_departure_airport\ntopic" as TopDepartureAirportTopic
    database "top_speed\ntopic" as TopSpeedTopic
    database "top_airline\ntopic" as TopAirlineTopic
    database "total_flight\ntopic" as TotalFlightTopic
}

FlightTopic --> API
TopArrivalAirportTopic --> API
TopDepartureAirportTopic --> API
TopSpeedTopic --> API
TopAirlineTopic --> API
TotalFlightTopic --> API
API ..> client : flights
API ..> client : topElementsChanged
API ..> client : totalElementsChanged
@enduml
