@startuml
title kafka-flightstream-api architecture

[kafka-flightstream-api] as API
[Client] as client

interface "Schema Registry" as SchemaRegistry

node Kafka {
    database "flight_received\ntopic" as FlightTopic
    database "top_arrival_airport\ntopic" as ArrivalAirportTopic
    database "top_departure_airport\ntopic" as DepartureAirportTopic
    database "top_speed\ntopic" as SpeedTopic
    database "top_airline\ntopic" as AirlineTopic
}

FlightTopic --> API
ArrivalAirportTopic --> API
DepartureAirportTopic --> API
SpeedTopic --> API
AirlineTopic --> API
API <-- SchemaRegistry
API ..> client : flights
API ..> client : topElementsChanged
@enduml
